### ISSUE TITLE
Questions about camera intrinsics

### ISSUE THREAD

**Issue by Jemmagu** [AAnoosheh/ToDayGAN#16]
Hi, @AAnoosheh ,

I use your test code and pretrained model to test my own testset, which is a little bit different from Oxford dataset, because mine contains more grasses and trees, and the buildings may look diferent. The night-to-day transformation results seem unsatisfying.

Since you mentioned that 'Because of sesitivity to instrinsic camera characteristics, testing should ideally be on the same Oxford dataset photos ', so how does the intrinsic influence the night-to-day transformation result? How can I change the camera intrinsic in the code?

Really hope to get your reply. Thanks in advance!

**Comment by AAnoosheh** [comment]
Hi,

The instrinsics refer to camera lens shape, distortion, color range, motion blur, FOV, etc., and these cannot be changed via code, unfortunately.

You would need to retrain on your dataset, since the camera used in the Oxford dataset produces very unique images, and neural networks are highly sensitive to changes in the aforementioned image statistics.

Best,
Asha
