### ISSUE TITLE
How can I get the training data?

### ISSUE THREAD

**Issue by Sweetclover** [AAnoosheh/ToDayGAN#18]

**Comment by AAnoosheh** [comment]
Hi,

You can download and process images from the Oxford RobotCar dataset yourself here:
https://robotcar-dataset.robots.ox.ac.uk/datasets/

I used only cloudy/overcast weather conditions for my daytime images (due to sun overexposing the camera) and non-rainy weather for nighttime images (for consistency).

**Comment by Sweetclover** [comment]
Hope you are doing well!
    I think it is too hard  for me to process such many images by myself. Then I think I can't train the network without the training data. Can you package the training data you use for us to download? I will thank you very much!

**Comment by AAnoosheh** [comment]
I wish I could, but there’s licensing issues with me redistributing it.

Also it was on a university server, from which I graduated over a year ago, so I couldn’t even access it for you if I tried.

**Comment by AAnoosheh** [comment]
You don't need to download them all, of course.
Just like 2000-5000 per domain.

**Comment by Sweetclover** [comment]
Wish you a bright future！
       I think it is a interesting and valuable work! Should I download 2000-5000 cloudy/overcast weather images as daytime images  and 2000-5000  non-rainy weather images as nighttime images?

**Comment by AAnoosheh** [comment]
Exactly.
You'll also need to run their undistortion script to turn the images flat from fisheye lenses.

Thank you!
