### ISSUE TITLE
trying to understand the dataset folder structure.

### ISSUE THREAD

**Issue by IamExperimenting** [AAnoosheh/ToDayGAN#30]
Hi @AAnoosheh ,

Thanks for making this repo public. I'm working on converting the night images to day images. I would like to get clarified on the dataset folder structure.

is it something that should look like this? or are any changes required? if you find the below folder structure is wrong, could you please provide the right structure?

```
---dataset
      |----train0
      |         |---day_image1.jpg
      |         |---day_image2.jpg
      |----train1
      |         |---night_image1.jpg
      |         |---night_image1.jpg
      |----test0
      |         |---day_image1.jpg
      |         |---day_image2.jpg
      |----test1
      |         |---night_image1.jpg
      |         |---night_image1.jpg
```
is the command right for the above folder structure?
```
python train.py --name night_to_day1 --dataroot ./datasets/train --n_domains 1 --niter40 

```

**Comment by AAnoosheh** [comment]
Hi the folder structure is okay. It will simply load both train and test in alphabetical order and assume the order matches for both.  
(The only time it has to be Day first, Night second is when using my pretrained model, since that's the order I trained it with)

The only problem I spot is `n_domains` should be 2 (day & night are our domains)

Thanks!
