### ISSUE TITLE
what number should I put for n domain in order translate from night to day?

### ISSUE THREAD

**Issue by ziyanghong** [AAnoosheh/ToDayGAN#5]
Hi Asha, thanks for sharing the code! I try the command: "python3 test.py --phase test --serial_test --name robotcar_2day --dataroot ./datasets/ --n_domains 2  --which_epoch 150" in order to translate night images to day images, but it dose not work, and could you tell me which weight file to use?

Thanks! @AAnoosheh

**Comment by AAnoosheh** [comment]
Hello,

N_domains remains 2 because there is Night & Day (two domains)
And the weight file is the one I uploaded in the Readme link.

But you seem to have not put a folder under ./datasets/ in your command.

You need another folder with images there, and two subfolders inside that called test0 & test1, with day and night images, respectively.
You can leave test0 empty since we don't care about day->night direction, but the folder just needs to exist since my prereained model was trained with Day being domain 0 and Night being 1.

There's a link to the Oxford RobotCar dataset where you can download files and undistort them using their script. We cannot upload the images we used from it due to it being their property.

**Comment by ziyanghong** [comment]
@AAnoosheh  Thanks for quick reply! The problem is that I only create a test_00 folder under /datasets so that it is night to night!
