### ISSUE TITLE
About the problem which I don't know how to  classify

### ISSUE THREAD

**Issue by YangyangQu** [AAnoosheh/ToDayGAN#7]
Hi Asha, I'm sorry to bother you! I try the command: " python train.py --name today1 --dataroot ./datasets/train --n_domains 2 --niter 10 --niter_decay 10" But i have the following problem:

File "train.py", line 38, in <module>
    visualizer.plot_current_errors(epoch, float(epoch_iter)/dataset_size, opt, errors)
  File "/home/chujian/ToDayGAN-master/util/visualizer.py", line 109, in plot_current_errors
    win=self.display_id)
  File "/home/chujian/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 335, in wrapped_f
    return f(*args, **kwargs)
  File "/home/chujian/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 1331, in line
    assert Y.ndim == 1 or Y.ndim == 2, 'Y should have 1 or 2 dim'
AssertionError: Y should have 1 or 2 dim

**Comment by AAnoosheh** [comment]
I inherited the Visdom code from CycleGAN, which the project originally branched from a while ago.
But I never actually used it myself.

In fact, if you run that command you quoted, it should not use Visdom whatsoever, so unless you are setting `--display_id` yourself, this should not be a problem.

If you want visualization, however, then I have no idea what to debug since it's code I've never looked at.
Sorry about that mate.
